"""cuthbert factorial filtering interface."""

from jax import numpy as jnp
from jax import random, tree
from jax.lax import scan

from cuthbert.factorial.types import Factorializer
from cuthbert.inference import Filter
from cuthbertlib.types import ArrayTree, ArrayTreeLike, KeyArray


def filter(
    filter_obj: Filter,
    factorializer: Factorializer,
    model_inputs: ArrayTreeLike,
    init_state: ArrayTree,
    *,
    output_factorial: bool = False,
    key: KeyArray | None = None,
) -> (
    ArrayTree | tuple[ArrayTree, ArrayTree]
):  # TODO: Can overload this function so the type checker knows that the output is an ArrayTree if output_factorial is True and a tuple[ArrayTree, ArrayTree, ArrayTree] if output_factorial is False
    """Applies offline factorial filtering for given model inputs.

    `model_inputs` should have leading temporal dimension of length T,
    where T is the number of time steps excluding the initial state.

    The output will have leading temporal dimension of length T + 1, and
    include the initial state as the first element.

    Parallel associative filtering is not supported for factorial filtering.

    Note that if output_factorial is True, this function will output a factorial state
    with first temporal dimension of length T + 1 and second factorial dimension of
    length F. Many of the factors will be unchanged across timesteps where they aren't
    relevant.

    Args:
        filter_obj: The filter inference object.
        factorializer: The factorializer object for the inference method.
        model_inputs: The model inputs for filtering
            (with leading temporal dimension of length T).
        init_state: The initial factorial state
            (with factorial dimension but no temporal dimension).
            Generated by `filter_obj.init_prepare` and then factorialized by
            `factorializer.factorialize_init_state`.
        output_factorial: If True, return a single state with first temporal dimension
            of length T + 1 and second factorial dimension of length F.
            If False, return a tuple of states.
            The first being the local states for each time step, i.e. first
            dimension of length T and no factorial dimension.
            The second being the final factorial state with first dimension of
            length F and no temporal dimension.
        key: The key for the random number generator.

    Returns:
        If output_factorial is True, returns a single state with first temporal dimension
            of length T + 1 and second factorial dimension of length F.
        If output_factorial is False, returns a tuple of
            (local states for each time step, final factorial state).
    """
    T = tree.leaves(model_inputs)[0].shape[0]

    if key is None:
        # This will throw error if used as a key, which is desired behavior
        # (albeit not a useful error, we could improve this)
        prepare_keys = jnp.empty(T)
    else:
        prepare_keys = random.split(key, T)

    def body_local(prev_factorial_state, prep_inp_and_k):
        prep_inp, k = prep_inp_and_k
        factorial_inds = factorializer.get_factorial_indices(prep_inp)
        factorial_inds = jnp.asarray(factorial_inds)

        # Extract and join local factors into joint local state
        local_state = factorializer.extract_and_join(prev_factorial_state, prep_inp)

        # Filter the joint local state
        prep_state = filter_obj.filter_prepare(prep_inp, key=k)
        filtered_joint_state = filter_obj.filter_combine(local_state, prep_state)

        # Marginalize and insert filtered joint local state into factorial state
        local_factorial_filtered_state = factorializer.marginalize(
            filtered_joint_state, len(factorial_inds)
        )
        factorial_state = factorializer.insert(
            local_factorial_filtered_state, prev_factorial_state, factorial_inds
        )
        return factorial_state, local_factorial_filtered_state

    if output_factorial:

        def body_factorial(prev_factorial_state, prep_inp_and_k):
            factorial_state, _ = body_local(prev_factorial_state, prep_inp_and_k)
            return factorial_state, factorial_state

        _, factorial_states = scan(
            body_factorial,
            init_state,
            (model_inputs, prepare_keys),
        )
        factorial_states = tree.map(
            lambda x, y: jnp.concatenate([x[None], y]),
            init_state,
            factorial_states,
        )

        return factorial_states

    else:
        final_factorial_state, local_states = scan(
            body_local,
            init_state,
            (model_inputs, prepare_keys),
        )
        return local_states, final_factorial_state
