"""cuthbert factorial filtering interface."""

from jax import numpy as jnp
from jax import random, tree, vmap
from jax.lax import scan

from cuthbert.factorial.types import Factorializer
from cuthbert.inference import Filter
from cuthbertlib.types import ArrayTree, ArrayTreeLike, KeyArray


def filter(
    filter_obj: Filter,
    factorializer: Factorializer,
    model_inputs: ArrayTreeLike,
    init_state: ArrayTreeLike,
    *,
    output_factorial: bool = False,
    key: KeyArray | None = None,
) -> (
    ArrayTree | tuple[ArrayTree, ArrayTree]
):  # TODO: Can overload this function so the type checker knows that the output is an ArrayTree if output_factorial is True and a tuple[ArrayTree, ArrayTree, ArrayTree] if output_factorial is False
    """Applies offline factorial filtering for given model inputs.

    `model_inputs` should have leading temporal dimension of length T,
    where T is the number of time steps excluding the initial state.

    The output will have leading temporal dimension of length T + 1, and
    include the initial state as the first element.

    Parallel associative filtering is not supported for factorial filtering.

    Note that if output_factorial is True, this function will output a factorial state
    with first temporal dimension of length T + 1 and second factorial dimension of
    length F. Many of the factors will be unchanged across timesteps where they aren't
    relevant.

    Args:
        filter_obj: The filter inference object.
        factorializer: The factorializer object for the inference method.
        model_inputs: The model inputs for filtering
            (with leading temporal dimension of length T).
        init_state: The initial factorial state
            (with factorial dimension but no temporal dimension).
            Generated by `filter_obj.init_prepare` and then factorialized by
            `factorializer.factorialize_init_state`.
        output_factorial: If True, return a single state with first temporal dimension
            of length T + 1 and second factorial dimension of length F.
            If False, return a tuple of states.
            The first being the local states for each time step, i.e. first
            dimension of length T and no factorial dimension.
            The second being the final factorial state with first dimension of
            length F and no temporal dimension.
        key: The key for the random number generator.

    Returns:
        If output_factorial is True, returns a single state with first temporal dimension
            of length T + 1 and second factorial dimension of length F.
        If output_factorial is False, returns a tuple of
            (local states for each time step, final factorial state).
    """
    T = tree.leaves(model_inputs)[0].shape[0]
    prepare_keys = _prepare_keys(key, T)

    def body_local(prev_factorial_state, prep_inp_and_k):
        prep_inp, k = prep_inp_and_k
        factorial_inds = factorializer.get_factorial_indices(prep_inp)
        factorial_inds = jnp.asarray(factorial_inds)

        # Extract and join local factors into joint local state
        local_state = factorializer.extract_and_join(prev_factorial_state, prep_inp)

        # Filter the joint local state
        prep_state = filter_obj.filter_prepare(prep_inp, key=k)
        filtered_joint_state = filter_obj.filter_combine(local_state, prep_state)

        # Marginalize and insert filtered joint local state into factorial state
        local_factorial_filtered_state = factorializer.marginalize(
            filtered_joint_state, len(factorial_inds)
        )
        factorial_state = factorializer.insert(
            local_factorial_filtered_state, prev_factorial_state, factorial_inds
        )
        return factorial_state, local_factorial_filtered_state

    if output_factorial:

        def body_factorial(prev_factorial_state, prep_inp_and_k):
            factorial_state, _ = body_local(prev_factorial_state, prep_inp_and_k)
            return factorial_state, factorial_state

        _, factorial_states = scan(
            body_factorial,
            init_state,
            (model_inputs, prepare_keys),
        )
        factorial_states = tree.map(
            lambda x, y: jnp.concatenate([x[None], y]),
            init_state,
            factorial_states,
        )

        return factorial_states

    else:
        final_factorial_state, local_states = scan(
            body_local,
            init_state,
            (model_inputs, prepare_keys),
        )
        return local_states, final_factorial_state


def synchronize(
    filter_obj: Filter,
    factorializer: Factorializer,
    model_inputs: ArrayTreeLike,
    factorial_state: ArrayTreeLike,
    *,
    key: KeyArray | None = None,
):
    """Apply a filter independently to each factor in a factorial state.

    Useful for synchronizing a factorial state so that factors distributions all
    apply to the same time.

    Args:
        filter_obj: The filter object used for single team dynamics-only updates.
        factorializer: The factorializer object used to extract individual factor states.
        model_inputs: The dynamics-only data for each team. Each attribute should have
            a leading factorial axis of length equal to the number of teams in
            the factorial state.
        factorial_state: The current factorial state, which typically encodes
            distributions for factors each at different times.
        key: The key for the random number generator.
    """
    num_factors = tree.leaves(model_inputs)[0].shape[0]
    prepare_keys = _prepare_keys(key, num_factors)

    factorial_extr_state = vmap(factorializer.extract, in_axes=(None, 0))(
        factorial_state, jnp.arange(num_factors)
    )
    state_prep = vmap(lambda inp, k: filter_obj.filter_prepare(inp, key=k))(
        model_inputs, prepare_keys
    )
    factorial_sync_state = vmap(filter_obj.filter_combine)(
        factorial_extr_state, state_prep
    )

    # Make sure sync state has the same shape as original state
    # I.e. log_normalizing_constant should be shape (,) not (num_factors,)
    factorial_sync_state = tree.map(
        _squeeze_sync_leaf,
        factorial_sync_state,
        factorial_state._replace(model_inputs=model_inputs),
    )

    return factorial_sync_state


def _prepare_keys(key: KeyArray | None, num_keys: int) -> KeyArray:
    if key is None:
        # This will throw error if used as a key, which is desired behavior
        # (albeit not a useful error, we could improve this)
        prepare_keys = jnp.empty(num_keys)
    else:
        prepare_keys = random.split(key, num_keys)
    return prepare_keys


def _squeeze_sync_leaf(sync_leaf, orig_leaf):
    if orig_leaf is None or sync_leaf is None:
        return sync_leaf
    if sync_leaf.shape == orig_leaf.shape:
        return sync_leaf
    if orig_leaf.ndim == 0:
        return sync_leaf[0]
    raise ValueError(
        f"Incompatible shapes: sync_leaf={sync_leaf.shape}, orig_leaf={orig_leaf.shape}"
    )
