r"""Linearized Taylor Kalman smoother.

Uses automatic differentiation to extract conditionally Gaussian parameters from log
densities of the dynamics and observation distributions.

This differs from `gaussian/moments`, which requires `mean` and `chol_cov`
functions as input rather than log densities.

I.e., we approximate conditional densities as

$$
p(y \mid x) \approx N(y \mid H x + d, L L^T),
$$

and potentials as

$$
G(x) \approx N(x \mid m, L L^T),
$$

where $L$ is the Cholesky factor of the covariance matrix.

See `cuthbertlib.linearize` for more details.
"""

from functools import partial

from jax import numpy as jnp
from jax import tree

from cuthbert.gaussian.kalman import (
    KalmanSmootherState,
    convert_filter_to_smoother_state,
    smoother_combine,
)
from cuthbert.gaussian.taylor.types import (
    GetDynamicsLogDensity,
)
from cuthbert.gaussian.types import (
    LinearizedKalmanFilterState,
)
from cuthbert.inference import Smoother
from cuthbertlib.kalman import smoothing
from cuthbertlib.linearize import linearize_log_density
from cuthbertlib.types import (
    ArrayTreeLike,
    KeyArray,
)


def build_smoother(
    get_dynamics_log_density: GetDynamicsLogDensity,
    rtol: float | None = None,
    ignore_nan_dims: bool = False,
    store_gain: bool = False,
    store_chol_cov_given_next: bool = False,
) -> Smoother:
    """Build linearized Taylor Kalman inference smoother.

    Args:
        get_dynamics_log_density: Function to get dynamics log density log p(x_t+1 | x_t)
            and linearization points (for the previous and current time points)
        rtol: The relative tolerance for the singular values of precision matrices
            when passed to `symmetric_inv_sqrt` during linearization.
            Cutoff for small singular values; singular values smaller than
            `rtol * largest_singular_value` are treated as zero.
            The default is determined based on the floating point precision of the dtype.
            See https://docs.jax.dev/en/latest/_autosummary/jax.numpy.linalg.pinv.html.
        ignore_nan_dims: Whether to treat dimensions with NaN on the diagonal of the
            precision matrices (found via linearization) as missing and ignore all rows
            and columns associated with them.
        store_gain: Whether to store the gain matrix in the smoother state.
        store_chol_cov_given_next: Whether to store the chol_cov_given_next matrix
            in the smoother state.

    Returns:
        Linearized Taylor Kalman smoother object, suitable for associative scan.
    """
    return Smoother(
        smoother_prepare=partial(
            smoother_prepare,
            get_dynamics_log_density=get_dynamics_log_density,
            rtol=rtol,
            ignore_nan_dims=ignore_nan_dims,
            store_gain=store_gain,
            store_chol_cov_given_next=store_chol_cov_given_next,
        ),
        smoother_combine=smoother_combine,
        convert_filter_to_smoother_state=partial(
            convert_filter_to_smoother_state,
            store_gain=store_gain,
            store_chol_cov_given_next=store_chol_cov_given_next,
        ),
        associative=True,
    )


def smoother_prepare(
    filter_state: LinearizedKalmanFilterState,
    get_dynamics_log_density: GetDynamicsLogDensity,
    model_inputs: ArrayTreeLike,
    rtol: float | None = None,
    ignore_nan_dims: bool = False,
    store_gain: bool = False,
    store_chol_cov_given_next: bool = False,
    key: KeyArray | None = None,
) -> KalmanSmootherState:
    """Prepare a state for a linearized Taylor Kalman smoother step.

    Args:
        filter_state: State generated by the linearized Taylor Kalman filter at the previous
            time point.
        get_dynamics_log_density: Function to get dynamics log density log p(x_t+1 | x_t)
            and linearization points (for the previous and current time points)
        model_inputs: Model inputs for the transition from t to t+1.
        rtol: The relative tolerance for the singular values of precision matrices
            when passed to `symmetric_inv_sqrt` during linearization.
            Cutoff for small singular values; singular values smaller than
            `rtol * largest_singular_value` are treated as zero.
            The default is determined based on the floating point precision of the dtype.
            See https://docs.jax.dev/en/latest/_autosummary/jax.numpy.linalg.pinv.html.
        ignore_nan_dims: Whether to treat dimensions with NaN on the diagonal of the
            precision matrices (found via linearization) as missing and ignore all rows
            and columns associated with them.
        store_gain: Whether to store the gain matrix in the smoother state.
        store_chol_cov_given_next: Whether to store the chol_cov_given_next matrix
            in the smoother state.
        key: JAX random key - not used.

    Returns:
        Prepared state for the Kalman smoother.
    """
    model_inputs = tree.map(lambda x: jnp.asarray(x), model_inputs)

    filter_mean = filter_state.mean
    filter_chol_cov = filter_state.chol_cov

    log_dynamics_density, linearization_point_prev, linearization_point_curr = (
        get_dynamics_log_density(filter_state, model_inputs)
    )

    F, c, chol_Q = linearize_log_density(
        log_dynamics_density,
        linearization_point_prev,
        linearization_point_curr,
        rtol=rtol,
        ignore_nan_dims=ignore_nan_dims,
    )

    state = smoothing.associative_params_single(
        filter_mean, filter_chol_cov, F, c, chol_Q
    )
    return KalmanSmootherState(
        elem=state,
        gain=state.E if store_gain else None,
        chol_cov_given_next=state.D if store_chol_cov_given_next else None,
        model_inputs=model_inputs,
    )
